### ISSUE TITLE
Release <VERSION> Checklist

### ISSUE THREAD

**Issue by j0hn** [Anaconda-Platform/anaconda-client#423]
## Release Checklist
- [ ] Release to beta
- [ ] Email Aamna about the beta release
- [ ] Update Internal Change Log: https://github.com/Anaconda-Server/anaconda-server/blob/develop/CHANGELOG.md
- [ ] If docs changed, coordinate release with Kerry
- [ ] Release to production
  - [ ] Ensure static assets are released as needed
- [ ] Create this ticket for next release and put it in the backlog
- [ ] Update the label to the installer on anaconda cloud (https://anaconda.org/binstar/binstar-server/files)
## Include CLI Client
- [ ] If Anaconda-Client changes then release with other changes
## Minor Release
- [ ] Update Public Docs Landing Page - http://docs.continuum.io/anaconda-server/index
      source: https://github.com/ContinuumIO/docs/blob/master/build/anaconda-server/index.rst
- [ ] Update Public Docs Change Log - http://docs.continuum.io/anaconda-server/changelog
- [ ] Post to @ everyone in FlowDock with an update announcing the release and providing the short summary of changes

**Comment by goanpeca** [comment]
@j0hn @abarto moved to the [RELEASE.md](https://github.com/Anaconda-Platform/anaconda-client/blob/develop/RELEASE.md#release-checklist)
